/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class utils_LoadLicenceC */

#ifndef _Included_utils_LoadLicenceC
#define _Included_utils_LoadLicenceC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     utils_LoadLicenceC
 * Method:    check_out_lic
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_utils_LoadLicenceC_check_1out_1lic
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
